name: Auto Patch Release

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  auto-patch-release:
    uses: ojarosch/github-actions/.github/workflows/auto-patch-release.yml@v1
    secrets: inherit
