name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  release:
    uses: ojarosch/github-actions/.github/workflows/go-release.yml@v1
    permissions:
      contents: write
      packages: write
      id-token: write
